server:
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: "GMT+8"
mybatis-plus:
  mapper-locations: classpath*:com.stephen.book.mapper/**Mapper.xml
  type-aliases-package: com.stephen.book.entity
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名
  global-config:
    db-config:
      id-type: auto
      db-type: mysql
      table-underline: true
      table-prefix:
